# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\ShortcutMemo\ui\add_shortcut.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddShortcut(object):
    def setupUi(self, AddShortcut):
        AddShortcut.setObjectName("AddShortcut")
        AddShortcut.resize(431, 323)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AddShortcut)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(AddShortcut)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.le_function = QtWidgets.QLineEdit(self.widget)
        self.le_function.setText("")
        self.le_function.setClearButtonEnabled(True)
        self.le_function.setObjectName("le_function")
        self.verticalLayout.addWidget(self.le_function)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.le_shortcut = QtWidgets.QLineEdit(self.widget)
        self.le_shortcut.setClearButtonEnabled(True)
        self.le_shortcut.setObjectName("le_shortcut")
        self.verticalLayout.addWidget(self.le_shortcut)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.te_note = QtWidgets.QTextEdit(self.widget)
        self.te_note.setObjectName("te_note")
        self.verticalLayout.addWidget(self.te_note)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(AddShortcut)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_add = QtWidgets.QPushButton(self.widget_2)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        spacerItem1 = QtWidgets.QSpacerItem(54, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget_2)

        self.retranslateUi(AddShortcut)
        QtCore.QMetaObject.connectSlotsByName(AddShortcut)

    def retranslateUi(self, AddShortcut):
        _translate = QtCore.QCoreApplication.translate
        AddShortcut.setWindowTitle(_translate("AddShortcut", "Add Software Shortcut"))
        self.label.setText(_translate("AddShortcut", "Function"))
        self.label_2.setText(_translate("AddShortcut", "Shortcut key"))
        self.label_3.setText(_translate("AddShortcut", "Note"))
        self.btn_add.setText(_translate("AddShortcut", "Add"))
