# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\ShortcutMemo\ui\add_name.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddName(object):
    def setupUi(self, AddName):
        AddName.setObjectName("AddName")
        AddName.resize(300, 130)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddName)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(AddName)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.le_name = QtWidgets.QLineEdit(AddName)
        self.le_name.setObjectName("le_name")
        self.verticalLayout.addWidget(self.le_name)
        self.widget = QtWidgets.QWidget(AddName)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(89, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_add = QtWidgets.QPushButton(self.widget)
        self.btn_add.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.btn_cancel = QtWidgets.QPushButton(self.widget)
        self.btn_cancel.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(AddName)
        QtCore.QMetaObject.connectSlotsByName(AddName)

    def retranslateUi(self, AddName):
        _translate = QtCore.QCoreApplication.translate
        AddName.setWindowTitle(_translate("AddName", "Add Software Name"))
        self.label.setText(_translate("AddName", "Software name:"))
        self.le_name.setPlaceholderText(_translate("AddName", "Please input software name"))
        self.btn_add.setText(_translate("AddName", "Add"))
        self.btn_cancel.setText(_translate("AddName", "Cancel"))
