# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\ShortcutMemo\ui\home_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeItem(object):
    def setupUi(self, HomeItem):
        HomeItem.setObjectName("HomeItem")
        HomeItem.resize(640, 175)
        self.w_item = QtWidgets.QWidget(HomeItem)
        self.w_item.setGeometry(QtCore.QRect(70, 50, 501, 61))
        self.w_item.setObjectName("w_item")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.w_item)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.w_item)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(288, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.w_item)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.w_item)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(HomeItem)
        QtCore.QMetaObject.connectSlotsByName(HomeItem)

    def retranslateUi(self, HomeItem):
        _translate = QtCore.QCoreApplication.translate
        HomeItem.setWindowTitle(_translate("HomeItem", "Item"))
        self.label.setText(_translate("HomeItem", "名称"))
        self.pushButton.setText(_translate("HomeItem", "删除"))
        self.pushButton_2.setText(_translate("HomeItem", "导出"))
