# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\ShortcutMemo\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.sw_home = QtWidgets.QStackedWidget(self.centralwidget)
        self.sw_home.setGeometry(QtCore.QRect(120, 170, 371, 251))
        self.sw_home.setObjectName("sw_home")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.sw_home.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.sw_home.addWidget(self.page_2)
        Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "ShortcutMemo"))
