# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\ShortcutMemo\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sw_shortcut = QtWidgets.QStackedWidget(self.centralwidget)
        self.sw_shortcut.setObjectName("sw_shortcut")
        self.page_name = QtWidgets.QWidget()
        self.page_name.setObjectName("page_name")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_name)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lw_software_name = QtWidgets.QListWidget(self.page_name)
        self.lw_software_name.setObjectName("lw_software_name")
        self.verticalLayout_2.addWidget(self.lw_software_name)
        self.widget = QtWidgets.QWidget(self.page_name)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(286, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_add_name = QtWidgets.QPushButton(self.widget)
        self.btn_add_name.setObjectName("btn_add_name")
        self.horizontalLayout.addWidget(self.btn_add_name)
        spacerItem1 = QtWidgets.QSpacerItem(285, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget)
        self.sw_shortcut.addWidget(self.page_name)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.sw_shortcut.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.sw_shortcut)
        Main.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(Main)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menutest = QtWidgets.QMenu(self.menuBar)
        self.menutest.setObjectName("menutest")
        Main.setMenuBar(self.menuBar)
        self.action_test1 = QtWidgets.QAction(Main)
        self.action_test1.setObjectName("action_test1")
        self.action_test2 = QtWidgets.QAction(Main)
        self.action_test2.setObjectName("action_test2")
        self.menutest.addAction(self.action_test1)
        self.menutest.addAction(self.action_test2)
        self.menuBar.addAction(self.menutest.menuAction())

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "ShortcutMemo"))
        self.btn_add_name.setText(_translate("Main", "Add..."))
        self.menutest.setTitle(_translate("Main", "test"))
        self.action_test1.setText(_translate("Main", " test1"))
        self.action_test2.setText(_translate("Main", "test2"))
